/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MChildTraverse {

  private final String pElementName;
  private final MChildTraverse mChildTraverse = this;

  MChildTraverse(String pElementName) {
    if(pElementName == null) throw new NullPointerException();
    this.pElementName = pElementName;
  }

  String pElementName() {
    return this.pElementName;
  }

  private String rElementName() {
    return this.mChildTraverse.pElementName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("      traverse(e");
    sb.append(rElementName());
    sb.append(")");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
