/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MEndApplyParameter {

  MEndApplyParameter() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("node.e$end: End");
    return sb.toString();
  }

}
