/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MEndElementAccessor {

  private final String pPkg;
  private final MEndElementAccessor mEndElementAccessor = this;

  MEndElementAccessor(String pPkg) {
    if(pPkg == null) throw new NullPointerException();
    this.pPkg = pPkg;
  }

  String pPkg() {
    return this.pPkg;
  }

  private String rPkg() {
    return this.mEndElementAccessor.pPkg();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("  protected[");
    sb.append(rPkg());
    sb.append("] def internalGet$end: End = this.e$end");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
