/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MEndCaseConstructorParameter {

  MEndCaseConstructorParameter() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("e$end");
    return sb.toString();
  }

}
