/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MNormalExtractorParameter {

  private final String pElementName;
  private final MNormalExtractorParameter mNormalExtractorParameter = this;

  MNormalExtractorParameter(String pElementName) {
    if(pElementName == null) throw new NullPointerException();
    this.pElementName = pElementName;
  }

  String pElementName() {
    return this.pElementName;
  }

  private String rElementName() {
    return this.mNormalExtractorParameter.pElementName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("node.internalGet");
    sb.append(rElementName());
    return sb.toString();
  }

}
