/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MNormalExtractorType {

  private final String pElementType;
  private final MNormalExtractorType mNormalExtractorType = this;

  MNormalExtractorType(String pElementType) {
    if(pElementType == null) throw new NullPointerException();
    this.pElementType = pElementType;
  }

  String pElementType() {
    return this.pElementType;
  }

  private String rElementType() {
    return this.mNormalExtractorType.pElementType();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(rElementType());
    return sb.toString();
  }

}
