/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MNormalApplyParameterCast {

  private final String pCastType;
  private final MNormalApplyParameterCast mNormalApplyParameterCast = this;

  MNormalApplyParameterCast(String pCastType) {
    if(pCastType == null) throw new NullPointerException();
    this.pCastType = pCastType;
  }

  String pCastType() {
    return this.pCastType;
  }

  private String rCastType() {
    return this.mNormalApplyParameterCast.pCastType();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(".asInstanceOf[");
    sb.append(rCastType());
    sb.append("]");
    return sb.toString();
  }

}
