/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

import java.util.*;

public class MNormalApplyParameter {

  private final String pElementName;
  private final MNormalApplyParameter mNormalApplyParameter = this;
  private final List<Object> eNormalApplyParameterCast = new LinkedList<Object>();

  MNormalApplyParameter(String pElementName) {
    if(pElementName == null) throw new NullPointerException();
    this.pElementName = pElementName;
  }

  public MNormalApplyParameterCast newNormalApplyParameterCast(String pCastType) {
    MNormalApplyParameterCast lNormalApplyParameterCast = new MNormalApplyParameterCast(pCastType);
    this.eNormalApplyParameterCast.add(lNormalApplyParameterCast);
    return lNormalApplyParameterCast;
  }

  String pElementName() {
    return this.pElementName;
  }

  private String rElementName() {
    return this.mNormalApplyParameter.pElementName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("e");
    sb.append(rElementName());
    for(Object oNormalApplyParameterCast : this.eNormalApplyParameterCast) {
      sb.append(oNormalApplyParameterCast.toString());
    }
    sb.append(" ");
    return sb.toString();
  }

}
