/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

import java.util.*;

public class MPublicElementAccessor {

  private final String pElementName;
  private final MPublicElementAccessor mPublicElementAccessor = this;
  private final List<Object> ePublicElementType_TokenElementType = new LinkedList<Object>();

  MPublicElementAccessor(String pElementName) {
    if(pElementName == null) throw new NullPointerException();
    this.pElementName = pElementName;
  }

  public MPublicElementType newPublicElementType(String pElementType) {
    MPublicElementType lPublicElementType = new MPublicElementType(pElementType);
    this.ePublicElementType_TokenElementType.add(lPublicElementType);
    return lPublicElementType;
  }

  public MTokenElementType newTokenElementType() {
    MTokenElementType lTokenElementType = new MTokenElementType();
    this.ePublicElementType_TokenElementType.add(lTokenElementType);
    return lTokenElementType;
  }

  String pElementName() {
    return this.pElementName;
  }

  private String rElementName() {
    return this.mPublicElementAccessor.pElementName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("  def ");
    sb.append(rElementName());
    sb.append(": ");
    for(Object oPublicElementType_TokenElementType : this.ePublicElementType_TokenElementType) {
      sb.append(oPublicElementType_TokenElementType.toString());
    }
    sb.append(" = ");
    sb.append(System.getProperty("line.separator"));
    sb.append("    this.e");
    sb.append(rElementName());
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
