/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MAcceptNormalToken {

  private final String pTokenName;
  private final MAcceptNormalToken mAcceptNormalToken = this;

  MAcceptNormalToken(String pTokenName) {
    if(pTokenName == null) throw new NullPointerException();
    this.pTokenName = pTokenName;
  }

  String pTokenName() {
    return this.pTokenName;
  }

  private String rTokenName() {
    return this.mAcceptNormalToken.pTokenName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    new N");
    sb.append(rTokenName());
    sb.append("(text).setPos(new Position(line, pos))");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
