/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MAnonymousAltType {

  MAnonymousAltType() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    Type.TAnonymous");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
