/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MAnonymousProductionHeader {

  private final String pPkg;
  private final MAnonymousProductionHeader mAnonymousProductionHeader = this;
  private final MProduction mProduction;

  MAnonymousProductionHeader(String pPkg, MProduction mProduction) {
    if(pPkg == null) throw new NullPointerException();
    this.pPkg = pPkg;
    if(mProduction == null) throw new NullPointerException();
    this.mProduction = mProduction;
  }

  String pPkg() {
    return this.pPkg;
  }

  private String rPkg() {
    return this.mAnonymousProductionHeader.pPkg();
  }

  private String rName() {
    return this.mProduction.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("protected[");
    sb.append(rPkg());
    sb.append("] protected abstract class N");
    sb.append(rName());
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
