/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MCaseConstructorParameter {

  private final String pCaseName;
  private final MCaseConstructorParameter mCaseConstructorParameter = this;

  MCaseConstructorParameter(String pCaseName) {
    if(pCaseName == null) throw new NullPointerException();
    this.pCaseName = pCaseName;
  }

  String pCaseName() {
    return this.pCaseName;
  }

  private String rCaseName() {
    return this.mCaseConstructorParameter.pCaseName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("e");
    sb.append(rCaseName());
    return sb.toString();
  }

}
