/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MEndParameter {

  MEndParameter() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("l$end");
    return sb.toString();
  }

}
