/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MEndConstructorParameter {

  MEndConstructorParameter() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("private val e$end: End");
    return sb.toString();
  }

}
