/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MMarkerDeclaration {

  private final String pName;
  private final MMarkerDeclaration mMarkerDeclaration = this;

  MMarkerDeclaration(String pName) {
    if(pName == null) throw new NullPointerException();
    this.pName = pName;
  }

  String pName() {
    return this.pName;
  }

  private String rName() {
    return this.mMarkerDeclaration.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("  private var marker");
    sb.append(rName());
    sb.append(" = 0");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
