/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MNodeInternalTypeEnumEntry {

  private final String pName;
  private final MNodeInternalTypeEnumEntry mNodeInternalTypeEnumEntry = this;

  MNodeInternalTypeEnumEntry(String pName) {
    if(pName == null) throw new NullPointerException();
    this.pName = pName;
  }

  String pName() {
    return this.pName;
  }

  private String rName() {
    return this.mNodeInternalTypeEnumEntry.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    case object T");
    sb.append(rName());
    sb.append(" extends InternalType");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
