/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MNoMarker {

  private final MTransitionStateSingleton mTransitionStateSingleton;

  MNoMarker(MTransitionStateSingleton mTransitionStateSingleton) {
    if(mTransitionStateSingleton == null) throw new NullPointerException();
    this.mTransitionStateSingleton = mTransitionStateSingleton;
  }

  private String rPkg() {
    return this.mTransitionStateSingleton.pPkg();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("  protected[");
    sb.append(rPkg());
    sb.append("] def marker(lexer: Lexer) {");
    sb.append(System.getProperty("line.separator"));
    sb.append("  }");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
