/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MProtectedConstructor {

  private final String pPkg;
  private final MProtectedConstructor mProtectedConstructor = this;

  MProtectedConstructor(String pPkg) {
    if(pPkg == null) throw new NullPointerException();
    this.pPkg = pPkg;
  }

  String pPkg() {
    return this.pPkg;
  }

  private String rPkg() {
    return this.mProtectedConstructor.pPkg();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(" protected[");
    sb.append(rPkg());
    sb.append("]");
    return sb.toString();
  }

}
