/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MProductionLrTransitionTarget {

  private final String pNodeType;
  private final String pTarget;
  private final MProductionLrTransitionTarget mProductionLrTransitionTarget = this;

  MProductionLrTransitionTarget(String pNodeType, String pTarget) {
    if(pNodeType == null) throw new NullPointerException();
    this.pNodeType = pNodeType;
    if(pTarget == null) throw new NullPointerException();
    this.pTarget = pTarget;
  }

  String pNodeType() {
    return this.pNodeType;
  }

  String pTarget() {
    return this.pTarget;
  }

  private String rNodeType() {
    return this.mProductionLrTransitionTarget.pNodeType();
  }

  private String rTarget() {
    return this.mProductionLrTransitionTarget.pTarget();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    case ProductionType.T");
    sb.append(rNodeType());
    sb.append(" => L");
    sb.append(rTarget());
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
