/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MThisTarget {

  MThisTarget() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("this.");
    return sb.toString();
  }

}
