/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala;

public class MTokenElementType {

  MTokenElementType() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("Token");
    return sb.toString();
  }

}
