/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MAcceptIgnoredToken {

  MAcceptIgnoredToken() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    null");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
