/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MAcceptTokenNoMarker {

  private final MFinalStateSingleton mFinalStateSingleton;

  MAcceptTokenNoMarker(MFinalStateSingleton mFinalStateSingleton) {
    if(mFinalStateSingleton == null) throw new NullPointerException();
    this.mFinalStateSingleton = mFinalStateSingleton;
  }

  private String rBackCount() {
    return this.mFinalStateSingleton.pBackCount();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    val text = lexer.accept(");
    sb.append(rBackCount());
    sb.append(")");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
