/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MAlternativeNodeParent {

  MAlternativeNodeParent() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("Node");
    return sb.toString();
  }

}
