/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MNormalConstructorParameter {

  private final String pElementType;
  private final String pElementName;
  private final MNormalConstructorParameter mNormalConstructorParameter = this;

  MNormalConstructorParameter(String pElementType, String pElementName) {
    if(pElementType == null) throw new NullPointerException();
    this.pElementType = pElementType;
    if(pElementName == null) throw new NullPointerException();
    this.pElementName = pElementName;
  }

  String pElementType() {
    return this.pElementType;
  }

  String pElementName() {
    return this.pElementName;
  }

  private String rElementName() {
    return this.mNormalConstructorParameter.pElementName();
  }

  private String rElementType() {
    return this.mNormalConstructorParameter.pElementType();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("private val e");
    sb.append(rElementName());
    sb.append(": N");
    sb.append(rElementType());
    return sb.toString();
  }

}
