/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MNormalTokenLrTransitionTarget {

  private final String pNodeType;
  private final String pTarget;
  private final MNormalTokenLrTransitionTarget mNormalTokenLrTransitionTarget = this;

  MNormalTokenLrTransitionTarget(String pNodeType, String pTarget) {
    if(pNodeType == null) throw new NullPointerException();
    this.pNodeType = pNodeType;
    if(pTarget == null) throw new NullPointerException();
    this.pTarget = pTarget;
  }

  String pNodeType() {
    return this.pNodeType;
  }

  String pTarget() {
    return this.pTarget;
  }

  private String rNodeType() {
    return this.mNormalTokenLrTransitionTarget.pNodeType();
  }

  private String rTarget() {
    return this.mNormalTokenLrTransitionTarget.pTarget();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("        case InternalType.T_");
    sb.append(rNodeType());
    sb.append(" => L_");
    sb.append(rTarget());
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
