/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MReduceEndPop {

  MReduceEndPop() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("      val l$end = stack.pop.asInstanceOf[End]");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
