/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

public class MSetMarker {

  private final String pName;
  private final MSetMarker mSetMarker = this;
  private final MTransitionStateSingleton mTransitionStateSingleton;

  MSetMarker(String pName, MTransitionStateSingleton mTransitionStateSingleton) {
    if(pName == null) throw new NullPointerException();
    this.pName = pName;
    if(mTransitionStateSingleton == null) throw new NullPointerException();
    this.mTransitionStateSingleton = mTransitionStateSingleton;
  }

  String pName() {
    return this.pName;
  }

  private String rPkg() {
    return this.mTransitionStateSingleton.pPkg();
  }

  private String rName() {
    return this.mSetMarker.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("  protected[");
    sb.append(rPkg());
    sb.append("] def marker(lexer: Lexer) {");
    sb.append(System.getProperty("line.separator"));
    sb.append("    lexer.setMarker");
    sb.append(rName());
    sb.append(System.getProperty("line.separator"));
    sb.append("  }");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
