/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

import java.util.*;

public class MTransitionStateSingleton {

  private final String pNumber;
  private final String pPkg;
  private final MTransitionStateSingleton mTransitionStateSingleton = this;
  private final List<Object> eDefaultPackage_SpecifiedPackage = new LinkedList<Object>();
  private final List<Object> eSetMarker = new LinkedList<Object>();
  private final List<Object> eNoMarker = new LinkedList<Object>();
  private final List<Object> eTransitionTarget = new LinkedList<Object>();

  public MTransitionStateSingleton(String pNumber, String pPkg) {
    if(pNumber == null) throw new NullPointerException();
    this.pNumber = pNumber;
    if(pPkg == null) throw new NullPointerException();
    this.pPkg = pPkg;
  }

  public MSetMarker newSetMarker(String pName) {
    MSetMarker lSetMarker = new MSetMarker(pName, mTransitionStateSingleton);
    this.eSetMarker.add(lSetMarker);
    return lSetMarker;
  }

  public MNoMarker newNoMarker() {
    MNoMarker lNoMarker = new MNoMarker(mTransitionStateSingleton);
    this.eNoMarker.add(lNoMarker);
    return lNoMarker;
  }

  public MTransitionTarget newTransitionTarget(String pSymbol, String pTarget) {
    MTransitionTarget lTransitionTarget = new MTransitionTarget(pSymbol, pTarget);
    this.eTransitionTarget.add(lTransitionTarget);
    return lTransitionTarget;
  }

  public MDefaultPackage newDefaultPackage(String pLanguageName) {
    MDefaultPackage lDefaultPackage = new MDefaultPackage(pLanguageName);
    this.eDefaultPackage_SpecifiedPackage.add(lDefaultPackage);
    return lDefaultPackage;
  }

  public MSpecifiedPackage newSpecifiedPackage(String pLanguageName, String pPackage) {
    MSpecifiedPackage lSpecifiedPackage = new MSpecifiedPackage(pLanguageName, pPackage);
    this.eDefaultPackage_SpecifiedPackage.add(lSpecifiedPackage);
    return lSpecifiedPackage;
  }

  String pNumber() {
    return this.pNumber;
  }

  String pPkg() {
    return this.pPkg;
  }

  private String rNumber() {
    return this.mTransitionStateSingleton.pNumber();
  }

  private String rPkg() {
    return this.mTransitionStateSingleton.pPkg();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(new MHeader().toString());
    if(this.eDefaultPackage_SpecifiedPackage.size() > 0) {
      sb.append(System.getProperty("line.separator"));
    }
    for(Object oDefaultPackage_SpecifiedPackage : this.eDefaultPackage_SpecifiedPackage) {
      sb.append(oDefaultPackage_SpecifiedPackage.toString());
    }
    sb.append(System.getProperty("line.separator"));
    sb.append("object S_");
    sb.append(rNumber());
    sb.append(System.getProperty("line.separator"));
    sb.append("    extends TransitionState {");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    sb.append("  import Symbol._");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    for(Object oSetMarker : this.eSetMarker) {
      sb.append(oSetMarker.toString());
    }
    for(Object oNoMarker : this.eNoMarker) {
      sb.append(oNoMarker.toString());
    }
    sb.append(System.getProperty("line.separator"));
    sb.append("  protected[");
    sb.append(rPkg());
    sb.append("] def target(symbol: Symbol) = symbol match {");
    sb.append(System.getProperty("line.separator"));
    for(Object oTransitionTarget : this.eTransitionTarget) {
      sb.append(oTransitionTarget.toString());
    }
    sb.append("    case _ => null");
    sb.append(System.getProperty("line.separator"));
    sb.append("  }");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    sb.append("}");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
