/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.scala.macro;

import java.util.*;

public class MTraverser {

  private final List<Object> eDefaultPackage_SpecifiedPackage = new LinkedList<Object>();
  private final List<Object> eNormalTraverserCase = new LinkedList<Object>();

  public MTraverser() {
  }

  public MDefaultPackage newDefaultPackage(String pLanguageName) {
    MDefaultPackage lDefaultPackage = new MDefaultPackage(pLanguageName);
    this.eDefaultPackage_SpecifiedPackage.add(lDefaultPackage);
    return lDefaultPackage;
  }

  public MSpecifiedPackage newSpecifiedPackage(String pLanguageName, String pPackage) {
    MSpecifiedPackage lSpecifiedPackage = new MSpecifiedPackage(pLanguageName, pPackage);
    this.eDefaultPackage_SpecifiedPackage.add(lSpecifiedPackage);
    return lSpecifiedPackage;
  }

  public MNormalTraverserCase newNormalTraverserCase(String pCaseType) {
    MNormalTraverserCase lNormalTraverserCase = new MNormalTraverserCase(pCaseType);
    this.eNormalTraverserCase.add(lNormalTraverserCase);
    return lNormalTraverserCase;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(new MHeader().toString());
    if(this.eDefaultPackage_SpecifiedPackage.size() > 0) {
      sb.append(System.getProperty("line.separator"));
    }
    for(Object oDefaultPackage_SpecifiedPackage : this.eDefaultPackage_SpecifiedPackage) {
      sb.append(oDefaultPackage_SpecifiedPackage.toString());
    }
    sb.append(System.getProperty("line.separator"));
    sb.append("class Traverser {");
    sb.append(System.getProperty("line.separator"));
    sb.append("  def traverse(node: Node): Unit = node match {");
    sb.append(System.getProperty("line.separator"));
    for(Object oNormalTraverserCase : this.eNormalTraverserCase) {
      sb.append(oNormalTraverserCase.toString());
    }
    sb.append("    case _ => // do nothing");
    sb.append(System.getProperty("line.separator"));
    sb.append("  }");
    sb.append(System.getProperty("line.separator"));
    sb.append("}");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
